"""Update opportunites table with agent fields

Revision ID: 030422323a95
Revises: 25ce4f23c7d2
Create Date: 2026-03-15 22:36:28.017069

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '030422323a95'
down_revision: Union[str, None] = '25ce4f23c7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunites_immobilieres', sa.Column('titre', sa.String(length=500), nullable=True))
    op.add_column('opportunites_immobilieres', sa.Column('prix_m2', sa.Float(), nullable=True))
    op.add_column('opportunites_immobilieres', sa.Column('adresse', sa.Text(), nullable=True))
    op.add_column('opportunites_immobilieres', sa.Column('photos', sa.Text(), nullable=True))
    op.add_column('opportunites_immobilieres', sa.Column('travaux_estimes', sa.Float(), nullable=True))
    op.add_column('opportunites_immobilieres', sa.Column('rentabilite_nette', sa.Float(), nullable=True))
    op.add_column('opportunites_immobilieres', sa.Column('raison_score', sa.Text(), nullable=True))
    op.add_column('opportunites_immobilieres', sa.Column('risques', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunites_immobilieres', 'risques')
    op.drop_column('opportunites_immobilieres', 'raison_score')
    op.drop_column('opportunites_immobilieres', 'rentabilite_nette')
    op.drop_column('opportunites_immobilieres', 'travaux_estimes')
    op.drop_column('opportunites_immobilieres', 'photos')
    op.drop_column('opportunites_immobilieres', 'adresse')
    op.drop_column('opportunites_immobilieres', 'prix_m2')
    op.drop_column('opportunites_immobilieres', 'titre')
    # ### end Alembic commands ###
