"""Initial migration

Revision ID: 12a6802da060
Revises: 
Create Date: 2026-03-15 21:18:58.786416

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '12a6802da060'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locataires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('revenus_annuels', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_locataires_id'), 'locataires', ['id'], unique=False)
    op.create_table('opportunites_immobilieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_annonce', sa.String(length=500), nullable=False),
    sa.Column('source', sa.Enum('SELOGER', 'PAP', 'LEBONCOIN', 'BIENICI', 'LOGIC_IMMO', 'AUTRE', name='sourceannonce'), nullable=False),
    sa.Column('reference_annonce', sa.String(length=100), nullable=True),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=5), nullable=True),
    sa.Column('nb_pieces', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('loyer_estime', sa.Float(), nullable=True),
    sa.Column('rentabilite_brute', sa.Float(), nullable=True),
    sa.Column('score_rentabilite', sa.Integer(), nullable=True),
    sa.Column('score_emplacement', sa.Integer(), nullable=True),
    sa.Column('score_etat', sa.Integer(), nullable=True),
    sa.Column('score_global', sa.Integer(), nullable=True),
    sa.Column('date_detection', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('NOUVEAU', 'VU', 'CONTACTE', 'VISITE_PROGRAMMEE', 'OFFRE_FAITE', 'REJETE', 'ACQUIS', name='statutopportunite'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_annonce')
    )
    op.create_index(op.f('ix_opportunites_immobilieres_date_detection'), 'opportunites_immobilieres', ['date_detection'], unique=False)
    op.create_index(op.f('ix_opportunites_immobilieres_id'), 'opportunites_immobilieres', ['id'], unique=False)
    op.create_index(op.f('ix_opportunites_immobilieres_score_global'), 'opportunites_immobilieres', ['score_global'], unique=False)
    op.create_index(op.f('ix_opportunites_immobilieres_ville'), 'opportunites_immobilieres', ['ville'], unique=False)
    op.create_table('sci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('forme_juridique', sa.String(length=50), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.Column('siege_social', sa.Text(), nullable=True),
    sa.Column('gerant_nom', sa.String(length=200), nullable=True),
    sa.Column('gerant_prenom', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom'),
    sa.UniqueConstraint('siret')
    )
    op.create_index(op.f('ix_sci_id'), 'sci', ['id'], unique=False)
    op.create_table('biens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sci_id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=5), nullable=False),
    sa.Column('complement_adresse', sa.String(length=200), nullable=True),
    sa.Column('type_bien', sa.Enum('APPARTEMENT', 'STUDIO', 'MAISON', 'LOCAL_COMMERCIAL', 'IMMEUBLE', 'PARKING', 'AUTRE', name='typebien'), nullable=False),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('nb_pieces', sa.Integer(), nullable=True),
    sa.Column('etage', sa.Integer(), nullable=True),
    sa.Column('date_acquisition', sa.Date(), nullable=True),
    sa.Column('prix_acquisition', sa.Float(), nullable=True),
    sa.Column('valeur_actuelle', sa.Float(), nullable=True),
    sa.Column('dpe_classe', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'NON_RENSEIGNE', name='classedpe'), nullable=True),
    sa.Column('dpe_date_validite', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('LOUE', 'VACANT', 'TRAVAUX', 'VENTE', name='statutbien'), nullable=False),
    sa.ForeignKeyConstraint(['sci_id'], ['sci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biens_date_acquisition'), 'biens', ['date_acquisition'], unique=False)
    op.create_index(op.f('ix_biens_id'), 'biens', ['id'], unique=False)
    op.create_index(op.f('ix_biens_sci_id'), 'biens', ['sci_id'], unique=False)
    op.create_index(op.f('ix_biens_ville'), 'biens', ['ville'], unique=False)
    op.create_table('simulations_acquisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('opportunite_id', sa.Integer(), nullable=True),
    sa.Column('date_simulation', sa.Date(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('resultats_json', sa.JSON(), nullable=False),
    sa.Column('recommandation_ia', sa.String(length=20), nullable=True),
    sa.Column('recommandation_details', sa.JSON(), nullable=True),
    sa.Column('statut', sa.Enum('SIMULE', 'EN_COURS', 'REALISE', 'ABANDONNE', name='statutsimulation'), nullable=False),
    sa.ForeignKeyConstraint(['opportunite_id'], ['opportunites_immobilieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_acquisition_id'), 'simulations_acquisition', ['id'], unique=False)
    op.create_table('baux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.Integer(), nullable=False),
    sa.Column('locataire_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('date_resiliation', sa.Date(), nullable=True),
    sa.Column('loyer_mensuel', sa.Float(), nullable=False),
    sa.Column('charges_mensuelles', sa.Float(), nullable=False),
    sa.Column('depot_garantie', sa.Float(), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'TERMINE', 'RESILIE', 'PREAVIS', name='statutbail'), nullable=False),
    sa.ForeignKeyConstraint(['bien_id'], ['biens.id'], ),
    sa.ForeignKeyConstraint(['locataire_id'], ['locataires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baux_bien_id'), 'baux', ['bien_id'], unique=False)
    op.create_index(op.f('ix_baux_id'), 'baux', ['id'], unique=False)
    op.create_index(op.f('ix_baux_locataire_id'), 'baux', ['locataire_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sci_id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.Integer(), nullable=True),
    sa.Column('type_document', sa.Enum('FACTURE', 'RELEVE_BANCAIRE', 'TAXE_FONCIERE', 'BAIL', 'DIAGNOSTIC_DPE', 'DIAGNOSTIC_AMIANTE', 'STATUTS_SCI', 'KBIS', 'AUTRE', name='typedocument'), nullable=False),
    sa.Column('s3_url', sa.String(length=500), nullable=False),
    sa.Column('nom_fichier', sa.String(length=300), nullable=False),
    sa.Column('date_document', sa.Date(), nullable=True),
    sa.Column('uploaded_at', sa.Date(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bien_id'], ['biens.id'], ),
    sa.ForeignKeyConstraint(['sci_id'], ['sci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_bien_id'), 'documents', ['bien_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_sci_id'), 'documents', ['sci_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sci_id', sa.Integer(), nullable=False),
    sa.Column('compte_bancaire_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('categorie', sa.Enum('LOYER', 'CHARGES_COPRO', 'TAXE_FONCIERE', 'TRAVAUX', 'REMBOURSEMENT_CREDIT', 'ASSURANCE', 'HONORAIRES', 'FRAIS_BANCAIRES', 'AUTRE', name='transactioncategorie'), nullable=True),
    sa.Column('categorie_confidence', sa.Float(), nullable=True),
    sa.Column('bien_id', sa.Integer(), nullable=True),
    sa.Column('locataire_id', sa.Integer(), nullable=True),
    sa.Column('statut_validation', sa.Enum('EN_ATTENTE', 'VALIDE', 'REJETE', name='statutvalidation'), nullable=False),
    sa.Column('valide_par', sa.String(length=100), nullable=True),
    sa.Column('date_validation', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bien_id'], ['biens.id'], ),
    sa.ForeignKeyConstraint(['locataire_id'], ['locataires.id'], ),
    sa.ForeignKeyConstraint(['sci_id'], ['sci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_bien_id'), 'transactions', ['bien_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_sci_id'), 'transactions', ['sci_id'], unique=False)
    op.create_table('document_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extractions_document_id'), 'document_extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_extractions_id'), 'document_extractions', ['id'], unique=False)
    op.create_table('quittances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bail_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('montant_loyer', sa.Float(), nullable=False),
    sa.Column('montant_charges', sa.Float(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('montant_paye', sa.Float(), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PAYE', 'IMPAYE', 'PARTIEL', name='statutquittance'), nullable=False),
    sa.Column('fichier_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['bail_id'], ['baux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quittances_bail_id'), 'quittances', ['bail_id'], unique=False)
    op.create_index(op.f('ix_quittances_id'), 'quittances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quittances_id'), table_name='quittances')
    op.drop_index(op.f('ix_quittances_bail_id'), table_name='quittances')
    op.drop_table('quittances')
    op.drop_index(op.f('ix_document_extractions_id'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_document_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index(op.f('ix_transactions_sci_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_bien_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_documents_sci_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_bien_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_baux_locataire_id'), table_name='baux')
    op.drop_index(op.f('ix_baux_id'), table_name='baux')
    op.drop_index(op.f('ix_baux_bien_id'), table_name='baux')
    op.drop_table('baux')
    op.drop_index(op.f('ix_simulations_acquisition_id'), table_name='simulations_acquisition')
    op.drop_table('simulations_acquisition')
    op.drop_index(op.f('ix_biens_ville'), table_name='biens')
    op.drop_index(op.f('ix_biens_sci_id'), table_name='biens')
    op.drop_index(op.f('ix_biens_id'), table_name='biens')
    op.drop_index(op.f('ix_biens_date_acquisition'), table_name='biens')
    op.drop_table('biens')
    op.drop_index(op.f('ix_sci_id'), table_name='sci')
    op.drop_table('sci')
    op.drop_index(op.f('ix_opportunites_immobilieres_ville'), table_name='opportunites_immobilieres')
    op.drop_index(op.f('ix_opportunites_immobilieres_score_global'), table_name='opportunites_immobilieres')
    op.drop_index(op.f('ix_opportunites_immobilieres_id'), table_name='opportunites_immobilieres')
    op.drop_index(op.f('ix_opportunites_immobilieres_date_detection'), table_name='opportunites_immobilieres')
    op.drop_table('opportunites_immobilieres')
    op.drop_index(op.f('ix_locataires_id'), table_name='locataires')
    op.drop_table('locataires')
    # ### end Alembic commands ###
