"""Add transactions table

Revision ID: 25ce4f23c7d2
Revises: 12a6802da060
Create Date: 2026-03-15 21:51:40.325784

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '25ce4f23c7d2'
down_revision: Union[str, None] = '12a6802da060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
